# This file was generated by GoReleaser. DO NOT EDIT.
class VultrCli < Formula
  desc "Official command-line tool for Vultr services"
  homepage "https://github.com/vultr/vultr-cli"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/vultr/vultr-cli/releases/download/v0.2.1/vultr-cli_0.2.1_macOs_64-bit.tar.gz"
    sha256 "3e4cfac0bbaf2ee844efa408125932812b2635d664f4107c0ee1cf564bb5b35c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/vultr/vultr-cli/releases/download/v0.2.1/vultr-cli_0.2.1_linux_64-bit.tar.gz"
      sha256 "2d501bcbab01812a6a0479a0bafd99e88d5aa1ac47722a7b5373111c88345b03"
    end
  end
  
  depends_on "go"

  def install
    bin.install "vultr-cli"
    prefix.install_metafiles
  end

  test do
    output = shell_output("#{bin}/vultr-cli version 2>&1", 1)
    assert_match "Please export your VULTR API key as an environment variable, eg:\nexport VULTR_API_KEY='<api_key_from_vultr_account>'\n", output
  end
end
