# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VultrCli < Formula
  desc "Official command-line tool for Vultr services"
  homepage "https://github.com/vultr/vultr-cli"
  version "2.17.0"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vultr/vultr-cli/releases/download/v2.17.0/vultr-cli_2.17.0_macOs_64-bit.tar.gz"
      sha256 "73dea4c67a671f8b45ab02b6aa34b3a9392cfc180c386a8802b1dabed09558fd"

      def install
        bin.install "vultr-cli"
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vultr/vultr-cli/releases/download/v2.17.0/vultr-cli_2.17.0_macOs_arm64-bit.tar.gz"
      sha256 "d49b13ad4a96912e5332d9059f128332c1af6aa9aca8df995b68de4e3cc63b43"

      def install
        bin.install "vultr-cli"
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vultr/vultr-cli/releases/download/v2.17.0/vultr-cli_2.17.0_linux_arm64-bit.tar.gz"
      sha256 "47fe224b38aedeb6670a8e0c9f95a5c37c243327a8ff9fc161538b0979b58109"

      def install
        bin.install "vultr-cli"
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vultr/vultr-cli/releases/download/v2.17.0/vultr-cli_2.17.0_linux_64-bit.tar.gz"
      sha256 "a9719d5761112486b13a1a7293b083e665e96c31ea0944303fa67448783bf2b6"

      def install
        bin.install "vultr-cli"
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/vultr/vultr-cli/releases/download/v2.17.0/vultr-cli_2.17.0_linux_armv6.tar.gz"
      sha256 "6410c537503c3d180e81c16032ad6cc110ada6f513bf0ee8a219de8a33e6c9af"

      def install
        bin.install "vultr-cli"
        prefix.install_metafiles
      end
    end
  end

  test do
    output = shell_output("#{bin}/vultr-cli version 2>&1", 1)
    assert_match "Please export your VULTR API key as an environment variable or add `api-key` to your config file, eg:\nexport VULTR_API_KEY='<api_key_from_vultr_account>'\n", output
  end
end
