# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VultrCli < Formula
  desc "Official command-line tool for Vultr services"
  homepage "https://github.com/vultr/vultr-cli"
  version "3.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vultr/vultr-cli/releases/download/v3.0.3/vultr-cli_v3.0.3_macOs_arm64.tar.gz"
      sha256 "3d0b29cab5bacb3df90c07acc6430d5caa6ef355c69caf7af71f16337fff8538"

      def install
        bin.install "vultr-cli"
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vultr/vultr-cli/releases/download/v3.0.3/vultr-cli_v3.0.3_macOs_amd64.tar.gz"
      sha256 "cc18c4cf595a2b47bdbecfdbf4668af0d778e18b488340f1bf7fac22359835b0"

      def install
        bin.install "vultr-cli"
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/vultr/vultr-cli/releases/download/v3.0.3/vultr-cli_v3.0.3_linux_arm32-v6.tar.gz"
      sha256 "13119b82af6b2178a6ad3423133362cfcda7af31b2e64a654b119fe13eda2117"

      def install
        bin.install "vultr-cli"
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vultr/vultr-cli/releases/download/v3.0.3/vultr-cli_v3.0.3_linux_arm64.tar.gz"
      sha256 "b911785e2e7b60538c18cb596246e5f77fa5cc5f6851cf72cbc559101ced7f80"

      def install
        bin.install "vultr-cli"
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vultr/vultr-cli/releases/download/v3.0.3/vultr-cli_v3.0.3_linux_amd64.tar.gz"
      sha256 "9e7d0005e90e467bf0f2c445b2a98b6962bba037773f6558f375540173223c2c"

      def install
        bin.install "vultr-cli"
        prefix.install_metafiles
      end
    end
  end

  test do
    output = shell_output("#{bin}/vultr-cli version 2>&1", 1)
    assert_match "Please export your VULTR API key as an environment variable or add `api-key` to your config file, eg:\nexport VULTR_API_KEY='<api_key_from_vultr_account>'\n", output
  end
end
